- README.md
- retry.go
Just fixes a small mistake in the readme and synopsis comments.
> Fix link to examples in readme

- retry.go
At the current implementation after **last** retry (it will be no mo retries!) **fails** - we're waiting **additional time** before returning:
```
...
delayTime := config.delay * (1 << (n - 1))
time.Sleep((time.Duration)(delayTime) * config.units)
```
For example (5 attempts, 1 sec delay) we'll wait 1 sec * 2 ^ 4 = **16 sec**! before return error (despite we already know that err should be returned)
**I've added check to return without wait.**
> Return immediately if error occur in the last retry attempt (don’t wait)

- README.md
- options.go
- retry.go
- retry_test.go
This PR adds additional `Option`: `DelayType`. It allows to switch between different delay calculation algorithms. There are two for now: `FixedDelay` which takes the same delay value every iteration, and BackOffDelay which works as previously. BackOffDelay is default.
> Allow to configure fixed or back off delay

- options.go
- retry_test.go
As pointed in #17 there is a missing delay before the second attempt. Not sure if it is on purpose, but in case it's not here's the fix.
> Fix missing delay before second attempt

- retry.go
This allows O(1) memory to be used with retries, whenever `lastErrorOnly` is set.
Addresses #23.
> Allocated length of `errorLog` should be 1 and not config.attempts if `lastErrorOnly` is set to true in the config.

- README.md
- options.go
- retry.go
- retry_test.go
Issue #9 initially proposed having a random jitter component to the delay; however, PR #12 omitted the random jitter.  This PR adds both a `RandomDelay` (for jitter) and `CombineDelay` (to allow combining any number of delays).  In addition, the default delay changes from exponential backoff (`BackOffDelay`) to exponential backoff with random jitter (`BackOffDelay` & `RandomDelay`).
> Support random jitter combined with other delay options.

- options.go
- retry.go
- retry_test.go
This option ensures the delay between 2 retries can not exceed a specified duration
> Add a MaxDelay option

- options.go
- retry_test.go
Although we have MaxDelay option, that only kicks in after the
DelayTypeFunc calculation is done, and the calculation itself could
overflow.
For example, with initial delay of 1 second, the 34th retry would cause
the calculated back off delay to go negative, and the 35th retry will
cause it to go back to zero.
This is loosely ported from our implementation outside of the package:
https://github.com/reddit/baseplate.go/commit/660b6c5ff490eaf19c6ecc595762fe386d3ca5fc
> Avoid overflow in BackOffDelay and CombineDelay

- examples/custom_retry_function_test.go
- examples/delay_based_on_error_test.go
- examples/http_get_test.go
- go.mod
When using go modules with a version of v2+ and the project is in the root directory, the module name must be appended with the major version.
Fixes #45.
> fix: Resolve go module import path

- retry.go
- retry_test.go
When using `retry.Context(ctx)` where the cancelled context stops the retry loop, add the context to the error log - Unless last error only is set.
This allows for consumers to access the errors that have occurred throughout the retry loop easily.
Technically this is a breaking change as previously it would return the error from the context by default, however now it will return a `retry.Error` by default.
Fixes #51
> fix!: Context cancel add to errors

- retry.go
- retry_test.go
Hello! I found that contexts aren't 100% respected if you set your retry attempts to be infinite. The `Do` function would only respect it if the context was closed before any retry attempts were made. This PR is to make contexts completely respected while maintaining the same API.
> Add support for contexts during infinite attempts

- options.go
- retry.go
- retry_test.go
- Adds a config option that lets you swap out the timer used within the library.
- Mainly useful for testing purposes or sharing the same timer object/module in a user's repo with the library.
> Add timer config option

- options.go
- retry.go
- retry_test.go
This commit adds a new option for configuring attempts based on error type.
Fixes: #48 
Also adds unit tests for the new option.
> feat: add support for attempts based on error types

- retry.go
- retry_test.go
When using `retry.Context(ctx)` and context is canceled, `retry.Do` always overwrites last error as `context canceled`.
It is very dangerous if the last error overwritten by `retry.Do` should be recovered manually.
> fix bug that overwrites last error when context is canceled

- retry.go
Fixes a typo in the word 'errors', adds fullstops to improve readability on pkg.go.dev and slightly changes the wording of the comment.
> docs: fix typo and improve consistency of comment for Error.Unwrap

- retry.go
- retry_test.go
> fix: return last non-nil value when unwrapping errors

- retry.go
- retry_test.go
Fixes #80.
Based on #78 to update tests and avoid causing a failure due to a `nil` value being expected, as referenced below.
https://github.com/avast/retry-go/blob/54c42e0cca6b9bbb768b09ce9eeaa55df9788805/retry_test.go#L167
⚠️ This may be considered a breaking change because some consumers of the package may expect the length of the error to be the maximum number of attempts rather than the actual number.
> fix: reslice error log to remove nil values

- retry.go
- retry_test.go
> fix: zero attempt should return error when the error is either unrecoverable or context error

- README.md
- options.go
| Before | After |
|:------|:-----|
| <img width="400" alt="スクリーンショット 2023-05-13 15 58 18" src="https://github.com/avast/retry-go/assets/5842353/63b80fed-a241-4791-9b72-b54806ecf866"> | <img width="400" alt="スクリーンショット 2023-05-13 15 58 35" src="https://github.com/avast/retry-go/assets/5842353/0d22c082-baa8-4d31-9865-c561b18b7cd5"> |
> fix: markdown code block format

- retry.go
- retry_test.go
This PR removes `errorLog` slice pre-allocation with the assumption that most calls to `retry.Do` don't actually require retry. If this is wishful thinking, please let me know. Aside from the readability win, the benchmarks that I added show improvement around allocations & cpu cycles when no errors are encountered, as expected.
Here are the results of the benchmarks that this PR introduces:
```sh
$ go test -benchmem -run=^$ -bench ^BenchmarkDo github.com/avast/retry-go/v4 > old.txt
goos: darwin
goarch: amd64
pkg: github.com/avast/retry-go/v4
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
BenchmarkDo-16            	       3	 420393029 ns/op	    2197 B/op	      33 allocs/op
BenchmarkDoNoErrors-16    	 5136325	       230.7 ns/op	     368 B/op	       5 allocs/op
PASS
ok …
```
> remove error log pre-allocation and add benchmark

- examples/errors_history_test.go
Thank you for this nice library. For my use case, I wanted all the previous errors too even if the final call succeeded. It was simple to build that using this library, so I thought it makes a good example.
> Add an example which shows err history

- retry.go
The way `unrecoverableError` wraps an error can lead to potential panics. In `IsRecoverable`, an `unrecoverableError` is passed to `errors.Is` without an embedded error. This is problematic because any error type that implements the `Is` interface and expects to be able to call `Error()` will trigger a panic due to the embedded error being `nil`.
To fix this, we can implement `Error()` on `unrecoverableError` and handle the case where the embedded error is nil.
> fix potential panic in IsRecoverable

- README.md
- options.go
- retry.go
Hello, IMHO, the `Attemps(0)` approach leads to surprises as it has no clear meaning. 
So with this PR, instead of
```go
Attempts(0)
```
You should also be able to write
```go
UntilSucceeded()
```
And the code becomes much more clear to read and understand.
Attemps(0) will continue to work, but I think it should be removed in another major version, in favor of a more intuitive API.
Also, I've made small changes in docs.
> Introduce UntilSucceeded option to improve readability

- retry.go
- retry_test.go
see more in https://github.com/avast/retry-go/issues/113
> Fix the inconsistency in the number of times passed in onRetry

- .godocdown.tmpl
- README.md
[GoDoc has been moved to pkg.go.dev](https://go.dev/blog/godoc.org-redirect).
> Update link to docs

- go.mod
- retry.go
When consumers of `retry-go` use the context `Cause` feature (introduced in go 1.20), the Cause error is not being extracted.
> support context cancel cause
